### ISSUE TITLE
Possibility to change ports

### ISSUE THREAD

**Issue by diegomx** [ankane/setup-opensearch#2]
Is there a possibility to change the Opensearch service ports other than port 9200?

I've searched a lot for examples but couldn't find anything.

**Comment by ankane** [comment]
Hey @diegomx, there's not currently a way to set OpenSearch configuration, but you can fork and add `, '-E',  'http.port=9300'` to [this line](https://github.com/ankane/setup-opensearch/blob/656906e456fea4e80979f8cdadadf333b68d666e/index.js#L129).
